####  CONNECTION SPECIFIC ####
ansible_network_os: asa
ansible_become: no
ansible_become_method: enable
ansible_become_pass: wsi

####  CONFIGURATION SPECIFIC ####

lines:
  - network: 0.0.0.0 0.0.0.0
    transport_input: ssh
    nameif: inside