routing_instance:
  - protocol: eigrp
    area: 2017 ##AS number
    networks: 
      - "20.17.5.0/30"
      - "20.17.5.4/30" 
      - "20.17.5.8/30" 
      - "20.17.5.12/30"
      - "8.8.8.8/32"
  - protocol: ospf
    area: 0    
    networks:
      - "20.17.6.0/29"
  - protocol: ospf
    area: 1
    networks:
      - "192.168.10.0/24"
      - "192.168.20.0/24"
      - "192.168.30.0/24"
  - protocol: ospf
    area: 2
    networks:
      - "10.20.30.0/24"
      - "20.20.20.20/32"
  - protocol: bgp
    area: 65000 ##AS number
    networks:
      - "209.136.0.0/16"
      - "138.76.0.0/16"
  - protocol: bgp
    area: 65001 ##AS number
    networks:
      - "11.11.11.11/32"
      - "22.22.22.22/32"
  - protocol: bgp
    area: 65002 ##AS number
    networks:
      - "2.2.2.2/32"
  - protocol: bgp
    area: 65003 ##AS number
    networks:
      - "3.3.3.3/32"
  - protocol: ospfv3
    area: 0    
    networks:
      - "dead:beef:11::1/128"
      - "dead:beef:22::1/128"
      - "dead:beef:2::1/128"
      - "dead:beef:3::1/128"
      - "a1f:ea75:ca75::/64"
      - "2001::/64"

