---
- name: Configure interface parameters on ASA devices
  hosts: firewalls
  gather_facts: false
  tasks:
    - name: Configure interface parameters on ASA devices
      asa_config:
        lines:
          - nameif {{ item.nameif }}
          - security-level {{ item.security_level }}
          - description {{ item.description }}
          - ip address {{item.ipv4_address}}
        parents: interface {{item.interface_type}}{{item.interface_id}}
      when: item.ipv4_address is defined
      loop: "{{ l3_interfaces | default([]) }}"
      