---
- name: single run
  hosts: RADIUS
  gather_facts: false
  tasks:
    apt:
      pkg: 
        - freeradius
        - snmp
        - snmpd
        - tftpd-hpa
        - syslog-ng
      state: present