---
- name: debug
  hosts: routers
  gather_facts: false
  roles:
    - routing
#  tasks:
#    - ios_config:
#        lines:
#          - network 9.9.9.9 0.0.0.0 area 0
#        parents: router ospf 9




