---
- name: single run
  hosts: BR3
  gather_facts: false
  tasks:
    - name: Configure Dialer
      ios_config:
        lines:
          - ip address negotiated
          - ip authentication mode eigrp 2017 md5
          - ip authentication key-chain eigrp 2017 KC
          - encapsulation ppp
          - dialer pool 1
          - dialer-group 1
          - ppp authentication pap
          - ppp pap sent-username papuser password cisco1
          - no cdp enable
        parents: interface Dialer1
    - name: Apply PPPoE configuration to physical interface
      ios_config:
        lines: 
          - pppoe enable group global
          - pppoe-client dial-pool-number 1
        parents: interface GigabitEthernet0/1