---

- name: Get current datetime
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check system datetime
      shell: date +"%H:%M:%S %d %b %Y"
      register: system_datetime
    - name: Set datetime as fact
      set_fact: datetime={{ system_datetime.stdout }}
#    - debug: msg="var is {{ datetime }}"

- name: single run
  hosts: switches
  gather_facts: false
  roles:
    - vtp





