---
- name: Configure hostnames 
  hosts: all
  gather_facts: false
  tasks:
    - name: Configure hostnames on IOS devices 
      ios_config:
        lines: hostname {{ hostname }}
      when: (ansible_network_os == "ios")
    - name: Configure hostnames on ASA devices
      asa_config:
        lines: hostname {{ hostname }}
      when: (ansible_network_os == "asa")
    - name: Configure hostnames on Linux servers 
      hostname: 
        name: "{{ hostname }}"
      when: (ansible_network_os == "Linux")