---
- name: Get current datetime
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check system datetime
      shell: date +"%H:%M:%S %d %b %Y"
      register: system_datetime
    - name: Set datetime as fact
      set_fact: datetime={{ system_datetime.stdout }}

- name: Basic configuration
  hosts: all
  gather_facts: false
  roles: 
    - basic-config

- name: RBAC configuration
  hosts: BR3
  gather_facts: false
  roles: 
    - rbac

- name: Config archive configuration
  hosts: HQ1
  gather_facts: false
  roles: 
    - config-backup

- name: SNMP configuration
  hosts: HQ1:FW1
  gather_facts: false
  roles: 
    - snmp

- name: Switching configuration
  hosts: switches
  gather_facts: false
  roles: 
    - vtp 
    - vlans 
    - lag
    - stp
    - switchports

- name: DHCP snooping and ARP inspection configuration
  hosts: SW1
  gather_facts: false
  roles: 
    - dhcp-snooping
    - dai

- name: Routed interfaces and SSH configuration 
  hosts: all
  gather_facts: false
  roles: 
    - routed-ports
    - ssh

- name: Gather facts for hosts with static DHCP configuration
  hosts: RADIUS
  gather_facts: true

- name: DHCP server configuration
  hosts: HQ1
  gather_facts: false
  roles: 
    - dhcp-server

- name: Routing and ACLs configuration
  hosts: routers:firewalls
  gather_facts: false
  roles: 
    - acl
    - routing