---
- name: Get current datetime
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check system datetime
      shell: date +"%H:%M:%S %d %b %Y"
      register: system_datetime
    - name: Set datetime as fact
      set_fact: datetime={{ system_datetime.stdout }}

- name: Basic configuration
  hosts: all
  gather_facts: false
  roles: 
    - basic-config

- name: RBAC configuration
  hosts: BR3
  gather_facts: false
  roles: 
    - rbac

- name: Config archive configuration
  hosts: HQ1
  gather_facts: false
  roles: 
    - config-backup

- name: Switching configuration
  hosts: switches
  gather_facts: false
  roles: 
    - vtp 
    - vlans 
    - lag
    - stp
    - switchports

- name: DHCP snooping and ARP inspection configuration
  hosts: SW1
  gather_facts: false
  roles: 
    - dhcp-snooping
    - dai

## This one is required because linux hosts have separate interface for ansible management 
## and unable to check topology interface with ansible facts because it's in a separate net namespace
- name: Get mac-address
  hosts: RADIUS
  gather_facts: false
  tasks:
    - name: Extract interfaces information in non-management net namespace
      shell: ip netns exec {{item.namespace}} ip link show {{item.interface_type}}{{item.interface_id}}
      register: output
      when: 
        - item.namespace is defined
        - item.namespace != None
      loop: "{{l3_interfaces}}"
    - name: Set topology interface mac address as a fact for static DHCP reservation
      set_fact:
        "{{ item.stdout | regex_search('(enp[0-9]{1}[s][0-9]{1})') }}": 
          macaddress: "{{ item.stdout | regex_search('([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}') }}"
      loop: "{{output.results}}"

- name: DHCP server configuration
  hosts: HQ1
  gather_facts: false
  roles: 
    - dhcp-server

- name: Routed interfaces and SSH configuration 
  hosts: all
  gather_facts: false
  roles: 
    - routed-ports
    - ssh

- name: Syslog, tftp server configuration
  hosts: RADIUS
  gather_facts: false
  roles:
    - syslog-server
    - tftp-server

- name: SNMP and syslog configuration
  hosts: HQ1:FW1
  gather_facts: false
  roles: 
    - snmp
    - syslog-client

- name: Routing and ACLs configuration
  hosts: routers:firewalls
  gather_facts: false
  roles: 
    - acl
    - routing
    - routing-auth

- name: FHRP configuration
  hosts: HQ1:HQ2
  gather_facts: false
  roles: 
    - fhrp

- name: BGP ACLs
  hosts: HQ1
  gather_facts: false
  tasks:
    - name: Set BGP distribute list
      ios_config:
        lines: 
          - neighbor 20.17.5.1 distribute-list ACL_DENY_BGP_IN in
          - neighbor 192.168.30.253 distribute-list ACL_DENY_BGP_IN in
        parents: 
          - router bgp 65001
          - address-family ipv4

- name: Local routing policy
  hosts: HQ1
  gather_facts: false
  tasks:
    - name: Set route-map for local routing policy
      ios_config:
        lines:
          - match ip address ACL_RM_LP
          - set ip next-hop 20.17.5.1
        parents: route-map RM_LOCAL_POLICY permit 10
    - name: Set local routing policy
      ios_config:
        lines: ip local policy route-map RM_LOCAL_POLICY

- name: Configure routing redistribution
  hosts: BR2
  gather_facts: false
  tasks:
    - name: Set route-map for OSPF redistribution
      ios_config:
        lines: match ip address ACL_RED_OSPF
        parents: route-map RM_RED_OSPF permit 10
    - name: Configure OSPF redistribution
      ios_config:
        lines: redistribute ospf 1 metric 1000000 0 255 1 1500 route-map RM_RED_OSPF
        parents: router eigrp 2017

- name: Configure NAT
  hosts: HQ1:HQ2
  gather_facts: false
  tasks:
    - name: Configure NAT inside interfaces
      ios_config:
        lines: ip nat inside
        parents: interface GigabitEthernet0/1.101
      async: 20
      poll: 5
    - name: Configure NAT outside interfaces
      ios_config:
        lines: ip nat outside
        parents: interface GigabitEthernet0/2
      async: 20
      poll: 5
    - name: Configure NAT statement
      ios_config:
        lines: ip nat inside source list ACL_FOR_NAT interface GigabitEthernet0/2 overload

- name: Configure PPPoE server
  hosts: ISP
  gather_facts: false
  roles:
    - ip-pool
  tasks:
    - name: Configure Virtual-Template
      ios_config:
        lines:
          - mtu 1492
          - ip unnumbered GigabitEthernet0/4
          - ip authentication mode eigrp 2017 md5
          - ip authentication key-chain eigrp 2017 KC
          - peer default ip address pool PPPoE
          - ppp authentication pap
          - ppp pap sent-username papuser password cisco1
        parents: interface Virtual-Template1
    - name: Configure BBA group
      ios_config:
        lines: virtual-template 1
        parents: bba-group pppoe global
    - name: Apply PPPoE configuration to physical interface
      ios_config:
        lines: pppoe enable group global
        parents: interface GigabitEthernet0/4

- name: Configure PPPoE client
  hosts: BR3
  gather_facts: false
  tasks:
    - name: Configure Dialer
      ios_config:
        lines:
          - ip address negotiated
          - ip authentication mode eigrp 2017 md5
          - ip authentication key-chain eigrp 2017 KC
          - encapsulation ppp
          - dialer pool 1
          - dialer-group 1
          - ppp authentication pap
          - ppp pap sent-username papuser password cisco1
          - no cdp enable
        parents: interface Dialer1
    - name: Apply PPPoE configuration to physical interface
      ios_config:
        lines: 
          - pppoe enable group global
          - pppoe-client dial-pool-number 1
        parents: interface GigabitEthernet0/1

- name: Configure DMVPN hub
  hosts: HQ1
  gather_facts: false
  tasks:    
    - name: Configure DMVPN hub
      ios_config:
        lines:
          - ipv6 address FE80::11 link-local
          - ipv6 mtu 1400
          - ipv6 nhrp authentication wsi2017
          - ipv6 nhrp map multicast dynamic
          - ipv6 nhrp map multicast 11.11.11.11
          - ipv6 nhrp map 2001::11/64 11.11.11.11
          - ipv6 nhrp network-id 100
          - ipv6 nhrp nhs 2001::11
          - ipv6 nhrp shortcut
          - ipv6 nhrp redirect
          - ipv6 ospf network broadcast
          - ipv6 ospf priority 200
        parents: interface Tunnel100

- name: Configure DMVPN spokes
  hosts: HQ2:BR2:BR3
  gather_facts: false
  tasks:    
    - name: Configure DMVPN spokes
      ios_config:
        lines:
          - ipv6 mtu 1400
          - ipv6 nhrp authentication wsi2017
          - ipv6 nhrp map multicast 11.11.11.11
          - ipv6 nhrp map 2001::11/64 11.11.11.11
          - ipv6 nhrp network-id 100
          - ipv6 nhrp nhs 2001::11
          - ipv6 nhrp shortcut
          - ipv6 ospf network broadcast
          - ipv6 ospf priority 100
        parents: interface Tunnel100

- name: Configure WebVPN settings
  hosts: FW2
  gather_facts: false
  roles:
    - ip-pool
    - webvpn
    - group-policy

- name: Configure IPsec
  hosts: FW1:FW2
  gather_facts: false
  roles:    
    - tunnel-group
    - ipsec