---
- name: Get current datetime
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check system datetime
      shell: date +"%H:%M:%S %d %b %Y"
      register: system_datetime
    - name: Set datetime as fact
      set_fact: datetime={{ system_datetime.stdout }}

- name: Basic configuration
  hosts: all
  gather_facts: false
  roles: 
    - basic-config

- name: RBAC configuration
  hosts: BR3
  gather_facts: false
  roles: 
    - rbac

- name: Config archive configuration
  hosts: HQ1
  gather_facts: false
  roles: 
    - config-backup

- name: SNMP configuration
  hosts: HQ1:FW1
  gather_facts: false
  roles: 
    - snmp

- name: Switching configuration
  hosts: switches
  gather_facts: false
  roles: 
    - vtp 
    - vlans 
    - lag
    - stp
    - switchports

- name: DHCP snooping and ARP inspection configuration
  hosts: SW1
  gather_facts: false
  roles: 
    - dhcp-snooping
    - dai

- name: Routed interfaces and SSH configuration 
  hosts: all
  gather_facts: false
  roles: 
    - routed-ports
    - ssh

- name: Gather facts for hosts with static DHCP configuration
  hosts: RADIUS
  gather_facts: true

- name: DHCP server configuration
  hosts: HQ1
  gather_facts: false
  roles: 
    - dhcp-server

- name: Routing and ACLs configuration
  hosts: routers:firewalls
  gather_facts: false
  roles: 
    - acl
    - routing

- name: Local routing policy
  hosts: HQ1
  gather_facts: false
  tasks:
    - name: Set route-map for local routing policy
      ios_config:
        lines:
          - match ip address ACL_RM_LP
          - set ip next-hop 20.17.5.1
        parents: route-map RM_LOCAL_POLICY permit 10
    - name: Set local routing policy
      ios_config:
        lines: ip local policy route-map RM_LOCAL_POLICY

- name: Configure routing redistribution
  hosts: BR2
  gather_facts: false
  tasks:
    - name: Set route-map for OSPF redistribution
      ios_config:
        lines: match ip address ACL_RED_OSPF
        parents: route-map RM_RED_OSPF permit 10
    - name: Configure OSPF redistribution
      ios_config:
        lines: redistribute ospf 1 metric 1000000 0 255 1 1500 route-map RM_RED_OSPF
        parents: router eigrp 2017