####  CONNECTION SPECIFIC ####
ansible_host: 10.0.191.103

####  CONFIGURATION SPECIFIC ####
hostname: ISP

l3_interfaces:
  - interface_type: GigabitEthernet
    interface_id: 0/1
    description: INET11
    ipv4_address: 20.17.5.1/30
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/2
    description: INET22
    ipv4_address: 20.17.5.5/30
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/3
    description: INET2
    ipv4_address: 20.17.5.9/30
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/4
    description: INET3
    ipv4_address: 20.17.5.13/30
    shutdown: false
  - interface_type: Loopback
    interface_id: 100
    description: 
    ipv4_address: 8.8.8.8/32
    shutdown: false
  - interface_type: Loopback
    interface_id: 200
    description: 
    ipv4_address: 209.136.0.1/16
    shutdown: false
  - interface_type: Loopback
    interface_id: 300
    description: 
    ipv4_address: 138.76.0.1/16
    shutdown: false

bgp_router_id: 8.8.8.8
bgp_neighbors:
  - local_as: 65000
    neighbor: 20.17.5.2
    remote_as: 65001
  - local_as: 65000
    neighbor: 20.17.5.6
    remote_as: 65001
  - local_as: 65000
    neighbor: 20.17.5.10
    remote_as: 65002
  - local_as: 65000
    neighbor: 20.17.5.14
    remote_as: 65003

users:
  - username: papuser
    configured_password: cisco1
    password_type: password

ip_pools:
  - name: PPPoE
    range_start: 10.255.255.1