---

- name: Check VTP Operating Mode
  ios_command:
    commands: sh vtp status | i Operating Mode
  register: vtp_mode

- name: Render a Jinja2 template onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_vlan_config.j2"
  when: vtp_mode.stdout[0] is not search('Client')
    