---

- name: Install syslog-ng
  apt:
    name: syslog-ng
    state: present

- name: Render a Jinja2 template onto an {{ ansible_network_os | upper }} device
  template:
    src: "{{ansible_network_os | lower}}_syslog_config.j2"
    dest: "/etc/syslog-ng/conf.d/{{config_name}}"

- name: Create destination files
  file:
    path: "{{item.value}}"
    state: touch
    mode: u=rw,g=rw,o=rw
  loop: "{{destinations | d([]) }}"

- name: Check any running syslog instances
  find:
    paths: /run/
    use_regex: yes
    patterns: ['^syslog']
  register: find_result

- name: Kill running syslog processes
  shell: pkill -F {{item['path']}}
  loop: "{{ find_result.files | d([]) }}"

- name: Restart syslog-ng
  shell: ip netns exec {{item.namespace}} /usr/sbin/syslog-ng --pidfile=/run/syslog-ng-{{item.namespace}}.pid
  when: item.namespace is defined
  loop: "{{l3_interfaces | d([])}}"