---
#- debug:
#    msg: 
#      ospf configuration is called, area is {{ item.1.area }}, 
#      network is {{ item.0.ipv4_address.split(' ') | join('/') |  ipaddr('network') }} ,
#      wildcard is {{ item.0.ipv4_address.split(' ') | join('/') | ipaddr('hostmask') }},
#      process id is {{ ospf_process_id}}
- name: Configure OSPF networks on IOS devices
  ios_config:
    lines:
      - network {{ item.0.ipv4_address.split(' ') | join('/') |  ipaddr('network') }} {{ item.0.ipv4_address.split(' ') | join('/') | ipaddr('hostmask') }} area {{ item.1.area }} 
    parents: router ospf {{ ospf_process_id}}
  when: (ansible_network_os == "ios")

- name: Configure OSPF networks on ASA devices
  asa_config:
    lines:
      - network {{ item.0.ipv4_address.split(' ') | join('/') |  ipaddr('network') }} {{ item.0.ipv4_address.split(' ') | join('/') | ipaddr('netmask') }} area {{ item.1.area }} 
    parents: router ospf {{ ospf_process_id}}
  when: (ansible_network_os == "asa")