---

- name: Enable secure copy mode
  asa_config:
    lines: ssh scopy enable

- name: Check flash contents
  asa_command:
    commands: dir
  register: dir

- name: Copy AnyConnect package onto an {{ ansible_network_os | upper }} device
  shell: "sshpass -p '{{ansible_ssh_pass}}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{role_path}}/files/{{package_filename}} {{ansible_user}}@{{ansible_host}}:/{{package_filename}}"
  async: 300
  poll: 10
  when: dir.stdout[0] is not search(package_filename)

- name: Render a Jinja2 template onto an {{ ansible_network_os | upper }} device
  asa_config: 
    src: "{{ansible_network_os | lower}}_webvpn_config.j2"