---
# vars file for routing

routing_instance:
  - protocol: eigrp
    area: 2017 ##AS number
    ipv4_networks: 
      - INET11
      - INET22
      - INET2
      - INET3
      - Loopback100
  - protocol: ospf
    area: 0    
    ipv4_networks:
      - INET4
  - protocol: ospf
    area: 1
    ipv4_networks:
      - LAN1
      - LAN2
      - EDGE
  - protocol: ospf
    area: 2
    ipv4_networks:
      - LAN3
      - Loopback20
  - protocol: ospf
    area: 3
    ipv4_networks:
      - Loopback30
  - protocol: bgp
    area: 65000 ##AS number
    ipv4_networks:
      - Loopback200
      - Loopback300
  - protocol: bgp
    area: 65001 ##AS number
    ipv4_networks:
      - Loopback101
      - Loopback102
  - protocol: bgp
    area: 65002 ##AS number
    ipv4_networks:
      - Loopback2
  - protocol: bgp
    area: 65003 ##AS number
    ipv4_networks:
      - Loopback3
  - protocol: ospfv3
    area: 0    
    ipv6_networks:
      - Loopback101
      - Loopback102
      - Loopback2
      - Loopback3
      - LAN1
      - DMVPN
