---
#- debug:
#    msg: eigrp configuration is called

- name: Configure EIGRP networks on IOS devices
  ios_config:
    lines:
      - network {{ item.0.ipv4_address.split(' ') | join('/') |  ipaddr('network') }} {{ item.0.ipv4_address.split(' ') | join('/') | ipaddr('hostmask') }} 
    parents: router eigrp {{ item.1.area }}
  when: (ansible_network_os == "ios")

- name: Configure key chain
  ios_config:
    lines:
      - key-string {{ key_chain.key_string }}
    parents: 
      - key chain {{ key_chain.name }}
      - key {{ key_chain.key }}
  when: (ansible_network_os == "ios")
  

- name: Apply key chain on interface
  ios_config:
    lines:
      - ip authentication mode eigrp {{ item.1.area }} md5
      - ip authentication key-chain eigrp {{ item.1.area }} {{ key_chain.name }}
    parents: 
      - interface {{ item.0.interface_type }}{{ item.0.interface_id }}
  when: (ansible_network_os == "ios")

- name: Configure EIGRP networks on ASA devices
  asa_config:
    lines:
      - network {{ item.0.ipv4_address.split(' ') | join('/') |  ipaddr('network') }} {{ item.0.ipv4_address.split(' ') | join('/') | ipaddr('netmask') }}
    parents: router ospf {{ item.1.area }} 
  when: (ansible_network_os == "asa")