---
- name: Render a Jinja2 template for EIGRP onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_eigrp_config.j2"

- name: Render a Jinja2 template for OSPF onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_ospf_config.j2"

- name: Render a Jinja2 template for BGP onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_bgp_config.j2"

- name: Render a Jinja2 template for OSPFv3 onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_ospfv3_config.j2"
