---
- name: Render a Jinja2 template for EIGRP onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_eigrp_config.j2"

- name: Render a Jinja2 template for OSPF onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_ospf_config.j2"

- name: Render a Jinja2 template for BGP onto an {{ ansible_network_os | upper }} device
  ios_config: 
    src: "{{ansible_network_os | lower}}_bgp_config.j2"

#- template:
#    src: "{{ansible_network_os | lower}}_eigrp_config.j2"
#    dest: "./roles/routing/files/{{inventory_hostname}}_eigrp.cfg"

#- template:
#    src: "{{ansible_network_os | lower}}_ospf_config.j2"
#    dest: "./roles/routing/files/{{inventory_hostname}}_ospf.cfg"

#- template:
#    src: "{{ansible_network_os | lower}}_bgp_config.j2"
#    dest: "./roles/routing/files/{{inventory_hostname}}_bgp.cfg"

#- debug:
#    msg: "{{ l3_interfaces | d([]) | union(l3_subinterfaces | d([])) | map('extract', ipv4_address) | list }} "
#  when: "{{item.protocol == 'ospf'}}"
#  loop: "{{ l3_interfaces | d([]) | union(l3_subinterfaces | d([])) }}" 
#- debug:
#    msg: "{{'20.17.5.1/30' | ipaddr('subnet')}}"
