---

- name: Install syslog-ng
  apt:
    name: syslog-ng
    state: present

- name: Render a Jinja2 template onto an {{ ansible_network_os | upper }} device
  template:
    src: "{{ansible_network_os | lower}}_syslog_config.j2"
    dest: "/etc/syslog-ng/conf.d/{{config_name}}"
  notify: Restart syslog-ng

- name: Restart syslog-ng
  shell: ip netns exec {{item.namespace}} /usr/sbin/syslog-ng --pidfile=/run/syslog-ng-{{item.namespace}}.pid
  where: item.namespace is defined
  loop: "{{l3_interfaces | d([])}}"