####  CONNECTION SPECIFIC ####

####  CONFIGURATION SPECIFIC ####
hostname: HQ2

l3_interfaces:
  - interface_type: GigabitEthernet
    interface_id: 0/1
    description: SW3_uplink
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/2
    description: INET22
    ipv4_address: 20.17.5.6/30
    shutdown: false
  - interface_type: Loopback
    interface_id: 102
    description: 
    ipv4_address: 22.22.22.22/32
    ipv6_address: dead:beef:22::1/128
    shutdown: false
l3_subinterfaces:
  - interface_type: GigabitEthernet
    interface_id: 0/1
    vlan: 101
    description: LAN1
    ipv4_address: 192.168.10.253/24
    ipv6_address: a1f:ea75:ca75::0/64
    ipv6_address_option: eui-64
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/1
    vlan: 102
    description: LAN2
    ipv4_address: 192.168.20.253/24
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/1
    vlan: 103
    description: EDGE
    ipv4_address: 192.168.30.253/24
    shutdown: false

bgp_router_id: 20.17.5.6
bgp_neighbors:
  - local_as: 65001
    neighbor: 20.17.5.1
    remote_as: 65000
  - local_as: 65001
    neighbor: 192.168.30.254
    remote_as: 65001